#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (c) 2021 by Clemens Rabe <clemens.rabe@clemensrabe.de>
# All rights reserved.
# This file is part of tcmReceiver (https://github.com/seeraven/tcmReceiver)
# and is released under the "BSD 3-Clause License". Please see the LICENSE file
# that is included as part of this package.
#
"""Power counter main entry point."""


# -----------------------------------------------------------------------------
# Module Import
# -----------------------------------------------------------------------------
import sys

from tcm_receiver.command import tcm_receiver


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
if __name__ == "__main__":
    sys.exit(0 if tcm_receiver() else 1)


# -----------------------------------------------------------------------------
# EOF
# -----------------------------------------------------------------------------
